Repository autonomys/subspace, pull requests merged in 2024-01, with the labels that each got.

#2388 BugFix: Fix invalid state transition fraud proof generation
  crates/pallet-domains/src/tests.rs
  crates/sp-domains-fraud-proof/src/execution_prover.rs
  crates/sp-domains-fraud-proof/src/fraud_proof.rs
  crates/sp-domains-fraud-proof/src/host_functions.rs
  crates/sp-domains-fraud-proof/src/runtime_interface.rs
  crates/sp-domains-fraud-proof/src/verification.rs
  domains/client/domain-operator/src/tests.rs
Labels: need to audit

#2390 Domains: Staking v1.1
  crates/pallet-domains/src/benchmarking.rs
  crates/pallet-domains/src/lib.rs
  crates/pallet-domains/src/staking.rs
  crates/pallet-domains/src/staking_epoch.rs
  crates/pallet-domains/src/tests.rs
  crates/sp-domains/src/lib.rs
  crates/subspace-runtime/src/lib.rs
  test/subspace-test-runtime/src/lib.rs
Labels: need to audit

#2418 Ensure using the same `transaction_byte_fee` for both validating and executing consensus extrinsic
  crates/pallet-transaction-fees/src/lib.rs
Labels: consensus, need to audit

#2384 Use the consensus chain storage price to charge domain transaction fees
  Cargo.lock
  crates/pallet-domains/Cargo.toml
  crates/pallet-domains/src/block_tree.rs
  crates/pallet-domains/src/lib.rs
  crates/pallet-domains/src/tests.rs
  crates/sp-domains-fraud-proof/src/bundle_equivocation.rs
  crates/sp-domains-fraud-proof/src/fraud_proof.rs
  crates/sp-domains-fraud-proof/src/host_functions.rs
  crates/sp-domains-fraud-proof/src/lib.rs
  crates/sp-domains-fraud-proof/src/test_ethereum_tx.rs
  crates/sp-domains-fraud-proof/src/tests.rs
  crates/sp-domains-fraud-proof/src/verification.rs
  crates/sp-domains/src/lib.rs
  crates/subspace-malicious-operator/src/malicious_bundle_tamper.rs
  crates/subspace-runtime/src/lib.rs
  domains/client/block-preprocessor/Cargo.toml
  domains/client/block-preprocessor/src/inherents.rs
  domains/client/block-preprocessor/src/stateless_runtime.rs
  domains/client/domain-operator/src/aux_schema.rs
  domains/client/domain-operator/src/domain_block_processor.rs
  domains/client/domain-operator/src/fraud_proof.rs
  domains/client/domain-operator/src/tests.rs
  domains/pallets/block-fees/Cargo.toml
  domains/pallets/block-fees/src/fees.rs
  domains/pallets/block-fees/src/lib.rs
  domains/pallets/executive/src/lib.rs
  domains/pallets/executive/src/mock.rs
  domains/pallets/operator-rewards/src/lib.rs
  domains/primitives/block-fees/Cargo.toml
  domains/primitives/block-fees/src/lib.rs
  domains/primitives/runtime/src/lib.rs
  domains/runtime/evm/Cargo.toml
  domains/runtime/evm/src/lib.rs
  domains/test/primitives/src/lib.rs
  domains/test/runtime/evm/Cargo.toml
  domains/test/runtime/evm/src/lib.rs
  test/subspace-test-runtime/src/lib.rs
Labels: execution, need to audit

#2419 Staking: ensure withdrawals are constant compute while unlocking or slashing operator
  crates/pallet-domains/src/lib.rs
  crates/pallet-domains/src/staking.rs
  crates/pallet-domains/src/staking_epoch.rs
Labels: need to audit

#2431 Correctly derive the oldest receipt number
  Cargo.lock
  crates/pallet-domains/src/benchmarking.rs
  crates/pallet-domains/src/block_tree.rs
  crates/pallet-domains/src/lib.rs
  crates/sp-domains-fraud-proof/Cargo.toml
  crates/sp-domains-fraud-proof/src/bundle_equivocation.rs
  crates/sp-domains/src/lib.rs
  crates/subspace-runtime/src/lib.rs
  domains/client/domain-operator/Cargo.toml
  domains/client/domain-operator/src/aux_schema.rs
  domains/client/domain-operator/src/bundle_processor.rs
  domains/client/domain-operator/src/domain_block_processor.rs
  domains/client/relayer/src/worker.rs
  test/subspace-test-runtime/src/lib.rs
Labels: execution, gemini-3h
