Repository autonomys/subspace, pull requests merged in 2024-10, with the labels that each got.

#3080 Silence a bare link warning in rustdoc
  crates/subspace-farmer-components/src/file_ext.rs
Labels: documentation

#3062 Refactor piece and segment downloading into subspace-data-retrieval
  Cargo.lock
  crates/subspace-archiving/src/reconstructor.rs
  crates/subspace-service/src/sync_from_dsn/import_blocks.rs
  shared/subspace-data-retrieval/Cargo.toml
  shared/subspace-data-retrieval/src/lib.rs
  shared/subspace-data-retrieval/src/object_fetcher.rs
  shared/subspace-data-retrieval/src/piece_fetcher.rs
  shared/subspace-data-retrieval/src/piece_getter.rs
  shared/subspace-data-retrieval/src/segment_fetcher.rs
Labels: enhancement

#3081 Extract object mappings for remark_with_event and seed_history
  Cargo.lock
  crates/subspace-runtime/src/object_mapping.rs
  test/subspace-test-client/src/chain_spec.rs
  test/subspace-test-runtime/Cargo.toml
  test/subspace-test-runtime/src/lib.rs
Labels: enhancement

#3072 Remove problematic equivocation
  Cargo.lock
  crates/pallet-offences-subspace/Cargo.toml
  crates/pallet-offences-subspace/README.md
  crates/pallet-offences-subspace/src/lib.rs
  crates/pallet-offences-subspace/src/mock.rs
  crates/pallet-offences-subspace/src/tests.rs
  crates/pallet-subspace/Cargo.toml
  crates/pallet-subspace/README.md
  crates/pallet-subspace/src/benchmarking.rs
  crates/pallet-subspace/src/equivocation.rs
  crates/pallet-subspace/src/lib.rs
  crates/pallet-subspace/src/mock.rs
  crates/pallet-subspace/src/tests.rs
  crates/pallet-subspace/src/weights.rs
  crates/sc-consensus-subspace/src/block_import.rs
  crates/sc-consensus-subspace/src/slot_worker.rs
  crates/sc-consensus-subspace/src/verifier.rs
  crates/sp-consensus-subspace/src/lib.rs
  crates/sp-consensus-subspace/src/offence.rs
  crates/sp-consensus-subspace/src/tests.rs
  crates/subspace-fake-runtime-api/src/lib.rs
  crates/subspace-runtime/Cargo.toml
  crates/subspace-runtime/src/lib.rs
  crates/subspace-service/src/lib.rs
  test/subspace-test-runtime/Cargo.toml
  test/subspace-test-runtime/src/lib.rs
Labels: need to audit

#3108 Refactor archiver public API to return ArchiveBlockOutcome
  crates/pallet-subspace/src/mock.rs
  crates/sc-consensus-subspace-rpc/src/lib.rs
  crates/sc-consensus-subspace/src/archiver.rs
  crates/sc-consensus-subspace/src/lib.rs
  crates/sc-consensus-subspace/src/tests.rs
  crates/subspace-archiving/src/archiver.rs
  crates/subspace-archiving/tests/integration/archiver.rs
  crates/subspace-archiving/tests/integration/piece_reconstruction.rs
  crates/subspace-archiving/tests/integration/reconstructor.rs
  crates/subspace-core-primitives/src/objects.rs
  crates/subspace-farmer-components/benches/auditing.rs
  crates/subspace-farmer-components/benches/plotting.rs
  crates/subspace-farmer-components/benches/proving.rs
  crates/subspace-farmer-components/benches/reading.rs
  crates/subspace-service/src/lib.rs
  crates/subspace-service/src/rpc.rs
  test/subspace-test-client/src/lib.rs
Labels: refactor

#3117 Limit CI to 2 hours when a test hangs
  .github/workflows/rust.yml
Labels: devops

#3100 Generate object mappings incrementally
  crates/subspace-archiving/src/archiver.rs
  crates/subspace-archiving/src/reconstructor.rs
  crates/subspace-archiving/tests/integration/archiver.rs
  shared/subspace-data-retrieval/src/object_fetcher.rs
Labels: improvement

#3118 Deny unsafe object mapping subscriptions
  crates/sc-consensus-subspace-rpc/src/lib.rs
Labels: bug

#3123 Skip empty object mapping notifications
  crates/sc-consensus-subspace/src/archiver.rs
Labels: improvement

#3124 Don't fetch ignored genesis mappings
  crates/sc-consensus-subspace/src/archiver.rs
Labels: improvement

#3125 Add a --create-object-mappings node CLI option
  crates/sc-consensus-subspace/Cargo.toml
  crates/sc-consensus-subspace/src/archiver.rs
  crates/subspace-malicious-operator/src/bin/subspace-malicious-operator.rs
  crates/subspace-node/src/commands/run/consensus.rs
  crates/subspace-service/src/config.rs
  crates/subspace-service/src/lib.rs
Labels: enhancement, node

#3130 Rewrite README intros to be clearer
  crates/subspace-farmer/README.md
  crates/subspace-farmer/src/bin/subspace-farmer/utils.rs
  crates/subspace-node/Cargo.toml
  crates/subspace-node/README.md
  crates/subspace-node/src/commands/run.rs
Labels: documentation

#3131 Initial subspace-gateway binary which does nothing
  Cargo.lock
  README.md
  crates/subspace-gateway/Cargo.toml
  crates/subspace-gateway/README.md
  crates/subspace-gateway/src/commands.rs
  crates/subspace-gateway/src/commands/run.rs
  crates/subspace-gateway/src/main.rs
Labels: enhancement

#3138 Simplify command-line help phrasing
  crates/subspace-farmer/src/bin/subspace-farmer/commands/benchmark.rs
  crates/subspace-farmer/src/bin/subspace-farmer/commands/cluster.rs
  crates/subspace-farmer/src/bin/subspace-farmer/commands/cluster/controller.rs
  crates/subspace-farmer/src/bin/subspace-farmer/commands/cluster/farmer.rs
  crates/subspace-farmer/src/bin/subspace-farmer/commands/cluster/plotter.rs
  crates/subspace-farmer/src/bin/subspace-farmer/commands/farm.rs
  crates/subspace-farmer/src/bin/subspace-farmer/commands/shared/network.rs
  crates/subspace-networking/examples/benchmark.rs
  crates/subspace-networking/examples/random-walker.rs
  crates/subspace-networking/src/bin/subspace-bootstrap-node/main.rs
  crates/subspace-networking/src/node.rs
  crates/subspace-node/src/commands/run/consensus.rs
  crates/subspace-service/src/dsn.rs
Labels: documentation

#3139 Add an initial gateway RPC crate
  Cargo.lock
  crates/sc-consensus-subspace-rpc/src/lib.rs
  crates/subspace-gateway-rpc/Cargo.toml
  crates/subspace-gateway-rpc/README.md
  crates/subspace-gateway-rpc/src/lib.rs
Labels: enhancement

#3146 Minimise features used by RPC servers, support IPv6 CORS
  crates/sc-consensus-subspace-rpc/Cargo.toml
  crates/subspace-gateway-rpc/Cargo.toml
  crates/subspace-gateway/Cargo.toml
  crates/subspace-node/src/commands/run/consensus.rs
  crates/subspace-node/src/commands/run/domain.rs
  crates/subspace-service/Cargo.toml
  domains/client/eth-service/Cargo.toml
  domains/service/Cargo.toml
  test/subspace-test-service/Cargo.toml
Labels: improvement

#3137 Add DSN client to subspace-gateway binary
  Cargo.lock
  crates/subspace-gateway/Cargo.toml
  crates/subspace-gateway/README.md
  crates/subspace-gateway/src/commands/run.rs
  crates/subspace-gateway/src/commands/run/dsn.rs
  crates/subspace-gateway/src/main.rs
  crates/subspace-gateway/src/node_client.rs
Labels: enhancement

#3157 Add max object size and DSN listen on address arguments to gateway
  crates/subspace-gateway/src/commands/run.rs
  crates/subspace-gateway/src/commands/run/network.rs
  crates/subspace-gateway/src/commands/run/rpc.rs
Labels: improvement

#3176 Replace panic with error in snap sync
  crates/subspace-networking/src/node_runner.rs
  crates/subspace-service/src/sync_from_dsn/snap_sync.rs
Labels: bug, node

#3177 Exit on panics, rather than unwinding
  crates/subspace-farmer/src/bin/subspace-farmer/main.rs
  crates/subspace-gateway/src/commands.rs
  crates/subspace-gateway/src/main.rs
  crates/subspace-networking/src/bin/subspace-bootstrap-node/main.rs
  crates/subspace-node/src/commands.rs
  crates/subspace-node/src/commands/shared.rs
  crates/subspace-node/src/main.rs
Labels: bug

#3185 Stay at v3 Cargo.lock file format
  crates/subspace-node/Cargo.toml
Labels: devops

#3187 Exit when snap sync needs user intervention
  crates/subspace-service/src/lib.rs
  crates/subspace-service/src/sync_from_dsn/snap_sync.rs
Labels: improvement

#3198 proper existential deposit value
  crates/subspace-runtime/src/lib.rs
Labels: need to audit
