Repository autonomys/subspace, pull requests merged in 2024-08, with the labels that each got.

#2959 Fix submit receipt issues
  crates/pallet-domains/src/block_tree.rs
  crates/pallet-domains/src/lib.rs
  crates/sp-domains/src/lib.rs
  crates/subspace-runtime/src/lib.rs
  domains/client/domain-operator/src/domain_bundle_producer.rs
  domains/client/domain-operator/src/domain_bundle_proposer.rs
  test/subspace-test-runtime/src/lib.rs
Labels: need to audit

#2957 Work around spurious errors that only happen in some IDEs
  crates/pallet-feeds/src/mock.rs
  crates/sc-consensus-subspace/src/archiver.rs
  crates/subspace-runtime/src/lib.rs
  domains/pallets/executive/src/mock.rs
  test/subspace-test-runtime/src/lib.rs
Labels: refactor

#2979 Add RPC subscription for piece object mappings
  crates/sc-consensus-subspace-rpc/src/lib.rs
  crates/subspace-archiving/src/archiver.rs
  crates/subspace-core-primitives/src/objects.rs
Labels: enhancement, networking

#2986 Add DSN object mappings for system.remark, fix offsets
  crates/sc-consensus-subspace-rpc/src/lib.rs
  crates/sc-consensus-subspace/Cargo.toml
  crates/sc-consensus-subspace/src/archiver.rs
  crates/subspace-archiving/src/archiver.rs
  crates/subspace-archiving/tests/integration/archiver.rs
  crates/subspace-core-primitives/src/objects.rs
  crates/subspace-core-primitives/src/pieces.rs
  crates/subspace-runtime/src/object_mapping.rs
  domains/pallets/transporter/src/benchmarking.rs
Labels: enhancement, networking, core
