Repository autonomys/subspace, pull requests merged in 2024-12, with the labels that each got.

#3265 Remove OperatorSigningKey pallet storage
  crates/pallet-domains/src/lib.rs
  crates/pallet-domains/src/staking.rs
  crates/pallet-domains/src/staking_epoch.rs
  crates/sp-domains/src/lib.rs
  crates/subspace-fake-runtime-api/src/lib.rs
  crates/subspace-malicious-operator/src/malicious_bundle_producer.rs
  crates/subspace-runtime/src/lib.rs
  test/subspace-test-runtime/src/lib.rs
Labels: improvement, execution

#3276 Split produce_bundle into smaller methods
  domains/client/domain-operator/src/domain_bundle_producer.rs
Labels: refactor, execution

#3277 Move test-only code to TestBundleProducer
  crates/subspace-malicious-operator/src/malicious_bundle_producer.rs
  domains/client/domain-operator/src/domain_bundle_producer.rs
  domains/client/domain-operator/src/domain_worker.rs
  domains/client/domain-operator/src/operator.rs
  domains/client/domain-operator/src/tests.rs
Labels: refactor, execution

#3279 Minor fix and refactoring to staking
  crates/pallet-domains/src/staking.rs
  crates/pallet-domains/src/staking_epoch.rs
Labels: refactor, execution

#3285 Minor staking refactoring
  crates/pallet-domains/src/bundle_storage_fund.rs
  crates/pallet-domains/src/staking.rs
  crates/pallet-domains/src/staking_epoch.rs
Labels: execution

#3278 XDM: Message submission checks to avoid validating duplicate XDM
  crates/subspace-fake-runtime-api/src/lib.rs
  crates/subspace-malicious-operator/src/bin/subspace-malicious-operator.rs
  crates/subspace-node/src/commands/run.rs
  crates/subspace-runtime/src/lib.rs
  domains/client/cross-domain-message-gossip/src/aux_schema.rs
  domains/client/cross-domain-message-gossip/src/gossip_worker.rs
  domains/client/cross-domain-message-gossip/src/lib.rs
  domains/client/cross-domain-message-gossip/src/message_listener.rs
  domains/pallets/messenger/src/lib.rs
  domains/primitives/messenger/src/lib.rs
  domains/runtime/auto-id/src/lib.rs
  domains/runtime/evm/src/lib.rs
  domains/service/src/domain.rs
  domains/test/runtime/auto-id/src/lib.rs
  domains/test/runtime/evm/src/lib.rs
  test/subspace-test-runtime/src/lib.rs
  test/subspace-test-service/src/lib.rs
Labels: audit-P2

#3284 Stop panicking when mapping with only genesis block
  crates/sc-consensus-subspace/src/archiver.rs
Labels: bug, node

#3283 Give FraudProofVariant explicit codec indexes
  crates/sp-domains-fraud-proof/src/fraud_proof.rs
Labels: documentation

#3299 Make object retrieval RPC logging match HTTP logging
  crates/subspace-gateway-rpc/src/lib.rs
Labels: improvement

#3301 Simplify source piece & data handling during object retrieval
  crates/subspace-core-primitives/src/pieces.rs
  crates/subspace-core-primitives/src/segments.rs
  shared/subspace-data-retrieval/src/object_fetcher.rs
Labels: improvement

#3300 Fix next source piece index calculation
  crates/subspace-core-primitives/src/pieces.rs
  crates/subspace-core-primitives/src/segments.rs
  shared/subspace-data-retrieval/src/object_fetcher.rs
Labels: bug

#3293 Simplify gateway HTTP server code using typed parameters
  crates/subspace-gateway/src/commands/http.rs
  crates/subspace-gateway/src/commands/http/server.rs
  crates/subspace-gateway/src/commands/rpc.rs
Labels: refactor, networking

#3302 Update the consensus and domain existential deposit
  crates/subspace-runtime/src/lib.rs
  domains/primitives/runtime/src/lib.rs
  test/subspace-test-client/src/chain_spec.rs
  test/subspace-test-runtime/src/lib.rs
Labels: execution

#3313 Rename fraud proof type for clarity
  crates/sp-domains-fraud-proof/src/fraud_proof.rs
  crates/sp-domains-fraud-proof/src/storage_proof.rs
  crates/sp-domains-fraud-proof/src/verification.rs
  domains/client/domain-operator/src/fraud_proof.rs
Labels: refactor

#3322 Fix bug in cross-segment object retrieval
  shared/subspace-data-retrieval/src/object_fetcher.rs
Labels: bug, networking

#3326 Fix panic when searching for archived block data
  crates/sc-consensus-subspace/src/archiver.rs
Labels: bug

#3314 Create invalid extrinsics fraud proof storage, and move block randomness into it
  crates/pallet-domains/src/lib.rs
  crates/sp-domains-fraud-proof/src/fraud_proof.rs
  crates/sp-domains-fraud-proof/src/host_functions.rs
  crates/sp-domains-fraud-proof/src/lib.rs
  crates/sp-domains-fraud-proof/src/storage_proof.rs
  crates/sp-domains-fraud-proof/src/verification.rs
  crates/subspace-runtime/src/lib.rs
  domains/client/domain-operator/src/fraud_proof.rs
  test/subspace-test-runtime/src/lib.rs
Labels: execution, breaking-runtime, host-function-change

#3315 Move timestamp into invalid extrinsics fraud proof storage
  crates/pallet-domains/src/lib.rs
  crates/pallet-domains/src/tests.rs
  crates/sp-domains-fraud-proof/src/storage_proof.rs
  crates/sp-domains-fraud-proof/src/verification.rs
  crates/subspace-runtime/src/lib.rs
  test/subspace-test-runtime/src/lib.rs
Labels: execution, breaking-runtime

#3320 Fix bug in fraud proof transaction fee value, and combine storage
  crates/pallet-domains/src/lib.rs
  crates/pallet-transaction-fees/src/lib.rs
  crates/sp-domains-fraud-proof/src/lib.rs
  crates/sp-domains-fraud-proof/src/storage_proof.rs
  crates/sp-domains-fraud-proof/src/verification.rs
  crates/subspace-runtime/src/lib.rs
  test/subspace-test-runtime/src/lib.rs
Labels: bug, consensus, execution, breaking-runtime

#3330 Add Teor to CODEOWNERS
  .github/CODEOWNERS
Labels: devops

#3332 Allow 3 bytes of segment padding in object fetcher
  crates/subspace-gateway/src/commands.rs
  shared/subspace-data-retrieval/src/object_fetcher.rs
Labels: bug, networking

#3333 Show panic backtraces in rust workflows
  .github/workflows/rust.yml
  .github/workflows/rustdoc.yml
Labels: devops

#3303 remove pallet-history-seeding and all related stuff
  Cargo.lock
  crates/pallet-history-seeding/Cargo.toml
  crates/pallet-history-seeding/README.md
  crates/pallet-history-seeding/src/benchmarking.rs
  crates/pallet-history-seeding/src/lib.rs
  crates/pallet-history-seeding/src/tests.rs
  crates/pallet-history-seeding/src/weights.rs
  crates/subspace-malicious-operator/src/chain_spec.rs
  crates/subspace-malicious-operator/src/malicious_bundle_producer.rs
  crates/subspace-node/src/chain_spec.rs
  crates/subspace-runtime/Cargo.toml
  crates/subspace-runtime/src/lib.rs
  crates/subspace-runtime/src/object_mapping.rs
  crates/subspace-runtime/src/signed_extensions.rs
  test/subspace-test-client/src/chain_spec.rs
  test/subspace-test-runtime/Cargo.toml
  test/subspace-test-runtime/src/lib.rs
Labels: breaking-runtime
