Repository autonomys/subspace, pull requests merged in 2024-09, with the labels that each got.

#2995 Don't wait for a full batch before returning DSN mappings
  crates/sc-consensus-subspace-rpc/src/lib.rs
Labels: bug

#2996 Serialize DSN mappings as a compact tuple
  crates/subspace-core-primitives/src/lib.rs
  crates/subspace-core-primitives/src/objects.rs
Labels: improvement

#3003 Add a RPC subscription which filters DSN mappings by object hash
  crates/sc-consensus-subspace-rpc/src/lib.rs
Labels: enhancement

#3014 Make serde hex attributes shorter
  crates/subspace-core-primitives/src/crypto.rs
  crates/subspace-core-primitives/src/lib.rs
  crates/subspace-core-primitives/src/pieces.rs
  crates/subspace-core-primitives/src/segments.rs
  crates/subspace-farmer/src/single_disk_farm.rs
  crates/subspace-rpc-primitives/src/lib.rs
Labels: refactor

#2990 Update consensus runtime transaction benchmark
  crates/pallet-domains/src/weights.rs
  crates/pallet-rewards/src/weights.rs
  crates/pallet-runtime-configs/src/weights.rs
  crates/pallet-subspace/src/lib.rs
  crates/pallet-subspace/src/weights.rs
  domains/pallets/messenger/src/tests.rs
  domains/pallets/messenger/src/weights.rs
  domains/pallets/transporter/src/lib.rs
  domains/pallets/transporter/src/weights.rs
Labels: need to audit

#3006 Add history seeding pallet
  Cargo.lock
  crates/pallet-history-seeding/Cargo.toml
  crates/pallet-history-seeding/README.md
  crates/pallet-history-seeding/src/benchmarking.rs
  crates/pallet-history-seeding/src/lib.rs
  crates/pallet-history-seeding/src/tests.rs
  crates/pallet-history-seeding/src/weights.rs
  crates/subspace-malicious-operator/src/chain_spec.rs
  crates/subspace-node/src/chain_spec.rs
  crates/subspace-runtime/Cargo.toml
  crates/subspace-runtime/src/lib.rs
Labels: need to audit

#3029 Fix object mapping offset calculations
  crates/sc-consensus-subspace-rpc/src/lib.rs
  crates/subspace-archiving/README.md
  crates/subspace-core-primitives/src/lib.rs
  crates/subspace-core-primitives/src/objects.rs
  crates/subspace-runtime/src/object_mapping.rs
Labels: bug, documentation

#3012 Implement initial version of subspace-data-retrieval crate
  Cargo.lock
  crates/subspace-core-primitives/src/pieces.rs
  shared/subspace-data-retrieval/Cargo.toml
  shared/subspace-data-retrieval/README.md
  shared/subspace-data-retrieval/src/lib.rs
  shared/subspace-data-retrieval/src/object_fetcher.rs
  shared/subspace-data-retrieval/src/piece_fetcher.rs
  shared/subspace-data-retrieval/src/segment_fetcher.rs
Labels: enhancement

#3040 Move versioning to BlockObjectMapping and PieceObjectMapping
  crates/subspace-archiving/src/archiver.rs
  crates/subspace-archiving/tests/integration/archiver.rs
  crates/subspace-core-primitives/src/objects.rs
  crates/subspace-runtime/src/object_mapping.rs
  test/subspace-test-runtime/src/lib.rs
Labels: improvement

#3048 Document shared crates in README.md
  README.md
Labels: documentation

#3013 Support shared hold id to have constant number of hold id
  crates/pallet-domains/src/bundle_storage_fund.rs
  crates/pallet-domains/src/domain_registry.rs
  crates/pallet-domains/src/lib.rs
  crates/pallet-domains/src/staking.rs
  crates/pallet-domains/src/staking_epoch.rs
  crates/pallet-domains/src/tests.rs
  crates/sp-domains/src/lib.rs
  crates/subspace-runtime-primitives/src/lib.rs
  crates/subspace-runtime/src/lib.rs
  domains/pallets/messenger/src/benchmarking.rs
  domains/pallets/messenger/src/lib.rs
  domains/pallets/messenger/src/mock.rs
  domains/pallets/messenger/src/tests.rs
  domains/pallets/transporter/src/mock.rs
  domains/primitives/messenger/src/messages.rs
  domains/primitives/runtime/src/lib.rs
  domains/runtime/auto-id/src/lib.rs
  domains/runtime/evm/src/lib.rs
  domains/test/runtime/auto-id/src/lib.rs
  domains/test/runtime/evm/src/lib.rs
  test/subspace-test-runtime/src/lib.rs
Labels: need to audit

#3049 Make Blake3Hash always encode as Hex in JSON
  crates/pallet-subspace/src/mock.rs
  crates/sc-consensus-subspace-rpc/src/lib.rs
  crates/sc-proof-of-time/src/verifier/tests.rs
  crates/sp-domains-fraud-proof/src/host_functions.rs
  crates/sp-domains-fraud-proof/src/verification.rs
  crates/sp-domains/src/merkle_tree.rs
  crates/subspace-core-primitives/src/checksum.rs
  crates/subspace-core-primitives/src/checksum/tests.rs
  crates/subspace-core-primitives/src/crypto.rs
  crates/subspace-core-primitives/src/lib.rs
  crates/subspace-core-primitives/src/objects.rs
  crates/subspace-farmer-components/benches/proving.rs
  crates/subspace-farmer-components/src/plotting.rs
  crates/subspace-farmer-components/src/reading.rs
  crates/subspace-farmer-components/src/sector.rs
  crates/subspace-farmer/src/bin/subspace-farmer/commands/benchmark.rs
  crates/subspace-farmer/src/disk_piece_cache.rs
  crates/subspace-farmer/src/farmer_cache/tests.rs
  crates/subspace-farmer/src/single_disk_farm.rs
  crates/subspace-farmer/src/single_disk_farm/plot_cache.rs
  crates/subspace-networking/src/behavior/persistent_parameters.rs
  crates/subspace-networking/src/constructor.rs
  crates/subspace-proof-of-space/src/shim.rs
  crates/subspace-verification/src/lib.rs
  domains/client/block-preprocessor/src/lib.rs
  domains/client/domain-operator/src/domain_bundle_proposer.rs
  domains/runtime/auto-id/src/lib.rs
  domains/runtime/evm/src/lib.rs
  domains/test/runtime/auto-id/src/lib.rs
  domains/test/runtime/evm/src/lib.rs
Labels: refactor, improvement

#3071 Spawn snap sync segment reconstruction into a blocking task
  crates/subspace-service/src/sync_from_dsn/import_blocks.rs
  crates/subspace-service/src/sync_from_dsn/snap_sync.rs
Labels: bug, performance
