Repository autonomys/subspace, pull requests merged in 2024-02, with the labels that each got.

#2498 Gemini 3g backport: improve the default connection limit management for DSN
  crates/subspace-farmer/src/single_disk_farm/plotting.rs
  crates/subspace-networking/src/constructor.rs
  crates/subspace-networking/src/node.rs
  crates/subspace-networking/src/node_runner.rs
  crates/subspace-networking/src/shared.rs
  crates/subspace-networking/src/utils/rate_limiter.rs
  crates/subspace-networking/src/utils/rate_limiter/resizable_semaphore.rs
  crates/subspace-networking/src/utils/rate_limiter/tests.rs
  crates/subspace-service/src/sync_from_dsn/import_blocks.rs
Labels: networking

#2497 Improve the default connection limit management for DSN.
  crates/subspace-farmer/src/single_disk_farm/plotting.rs
  crates/subspace-networking/src/constructor.rs
  crates/subspace-networking/src/node.rs
  crates/subspace-networking/src/node_runner.rs
  crates/subspace-networking/src/shared.rs
  crates/subspace-networking/src/utils/rate_limiter.rs
  crates/subspace-networking/src/utils/rate_limiter/resizable_semaphore.rs
  crates/subspace-networking/src/utils/rate_limiter/tests.rs
  crates/subspace-service/src/sync_from_dsn/import_blocks.rs
Labels: farmer, networking, node

#2416 Introduce the bundle storage fund
  crates/pallet-domains/src/block_tree.rs
  crates/pallet-domains/src/bundle_storage_fund.rs
  crates/pallet-domains/src/domain_registry.rs
  crates/pallet-domains/src/lib.rs
  crates/pallet-domains/src/staking.rs
  crates/pallet-domains/src/staking_epoch.rs
  crates/pallet-domains/src/tests.rs
  crates/pallet-transaction-fees/src/lib.rs
  crates/sp-domains-fraud-proof/src/bundle_equivocation.rs
  crates/sp-domains-fraud-proof/src/lib.rs
  crates/sp-domains/src/lib.rs
  crates/subspace-malicious-operator/src/malicious_bundle_tamper.rs
  crates/subspace-runtime-primitives/src/lib.rs
  crates/subspace-runtime/src/lib.rs
  domains/client/domain-operator/src/domain_bundle_proposer.rs
  test/subspace-test-runtime/src/lib.rs
Labels: execution, need to audit

#2516 Add check to the bundle slot and the proof-of-time
  Cargo.lock
  crates/pallet-domains/Cargo.toml
  crates/pallet-domains/src/lib.rs
  crates/pallet-domains/src/tests.rs
  crates/sc-consensus-subspace-rpc/src/lib.rs
  crates/sc-consensus-subspace/src/slot_worker.rs
  crates/sp-domains/src/lib.rs
  crates/subspace-malicious-operator/src/malicious_bundle_producer.rs
  crates/subspace-malicious-operator/src/malicious_domain_instance_starter.rs
  crates/subspace-node/src/commands/run/domain.rs
  crates/subspace-runtime/src/lib.rs
  domains/client/domain-operator/src/bundle_producer_election_solver.rs
  domains/client/domain-operator/src/domain_bundle_producer.rs
  domains/client/domain-operator/src/domain_worker.rs
  domains/client/domain-operator/src/lib.rs
  domains/client/domain-operator/src/tests.rs
  domains/client/domain-operator/src/utils.rs
  domains/service/src/domain.rs
  test/subspace-test-client/src/lib.rs
  test/subspace-test-runtime/src/lib.rs
  test/subspace-test-service/src/lib.rs
Labels: need to audit

#2527 Domains: Account for funds of each domain on Consensus chain
  Cargo.lock
  crates/pallet-domains/Cargo.toml
  crates/pallet-domains/src/benchmarking.rs
  crates/pallet-domains/src/block_tree.rs
  crates/pallet-domains/src/domain_registry.rs
  crates/pallet-domains/src/lib.rs
  crates/pallet-domains/src/runtime_registry.rs
  crates/pallet-domains/src/staking.rs
  crates/pallet-domains/src/staking_epoch.rs
  crates/pallet-domains/src/tests.rs
  crates/sp-domains-fraud-proof/src/fraud_proof.rs
  crates/sp-domains-fraud-proof/src/host_functions.rs
  crates/sp-domains-fraud-proof/src/lib.rs
  crates/sp-domains-fraud-proof/src/tests.rs
  crates/sp-domains-fraud-proof/src/verification.rs
  crates/sp-domains/src/core_api.rs
  crates/sp-domains/src/lib.rs
  crates/sp-domains/src/storage.rs
  crates/subspace-malicious-operator/src/chain_spec.rs
  crates/subspace-malicious-operator/src/malicious_bundle_producer.rs
  crates/subspace-malicious-operator/src/malicious_bundle_tamper.rs
  crates/subspace-node/src/chain_spec.rs
  crates/subspace-node/src/domain/evm_chain_spec.rs
  crates/subspace-runtime/src/lib.rs
  domains/client/block-preprocessor/src/lib.rs
  domains/client/block-preprocessor/src/stateless_runtime.rs
  domains/client/domain-operator/src/bundle_processor.rs
  domains/client/domain-operator/src/domain_block_processor.rs
  domains/client/domain-operator/src/domain_bundle_producer.rs
  domains/client/domain-operator/src/domain_bundle_proposer.rs
  domains/client/domain-operator/src/domain_worker.rs
  domains/client/domain-operator/src/fraud_proof.rs
  domains/client/domain-operator/src/operator.rs
  domains/client/domain-operator/src/tests.rs
  domains/pallets/block-fees/Cargo.toml
  domains/pallets/block-fees/src/lib.rs
  domains/pallets/messenger/Cargo.toml
  domains/pallets/transporter/Cargo.toml
  domains/pallets/transporter/src/lib.rs
  domains/primitives/runtime/Cargo.toml
  domains/primitives/runtime/src/lib.rs
  domains/runtime/evm/src/lib.rs
  domains/service/src/domain.rs
  domains/test/runtime/evm/src/lib.rs
  domains/test/service/src/domain.rs
  test/subspace-test-client/Cargo.toml
  test/subspace-test-client/src/chain_spec.rs
  test/subspace-test-client/src/domain_chain_spec.rs
  test/subspace-test-runtime/src/lib.rs
Labels: execution, need to audit

#2556 Improvements around unsafe
  crates/subspace-farmer-components/src/reading.rs
  crates/subspace-farmer-components/src/sector.rs
Labels: need to audit
