Repository autonomys/subspace, pull requests merged in 2025-05, with the labels that each got.

#3507 libp2p-req-resp: don't fail request on DialError::DialPeerConditionFalse
  Cargo.lock
  Cargo.toml
Labels: bug, networking, node

#3513 Fix illegal tx inconsistency
  Cargo.lock
  domains/client/block-preprocessor/src/lib.rs
  domains/client/block-preprocessor/src/stateless_runtime.rs
  domains/client/domain-operator/Cargo.toml
  domains/client/domain-operator/src/bundle_processor.rs
  domains/client/domain-operator/src/domain_block_processor.rs
  domains/client/domain-operator/src/domain_bundle_proposer.rs
  domains/client/domain-operator/src/domain_worker.rs
  domains/client/domain-operator/src/operator.rs
Labels: execution, audit-P2

#3517 Ignore rustsec advisories for wasmtime
  .github/workflows/rustsec-audit.yml
Labels: devops, upstream

#3506 Fix DSN snap sync block import gap errors
  Cargo.lock
  crates/sc-domains/src/domain_block_er/receipt_receiver.rs
  crates/subspace-farmer/src/bin/subspace-farmer/commands/shared/network.rs
  crates/subspace-service/src/sync_from_dsn.rs
  crates/subspace-service/src/sync_from_dsn/import_blocks.rs
  crates/subspace-service/src/sync_from_dsn/segment_header_downloader.rs
  domains/client/domain-operator/Cargo.toml
  domains/client/domain-operator/src/snap_sync.rs
Labels: bug, node

#3519 Fix off-by-one error in snap sync block reconstruction
  crates/subspace-service/src/sync_from_dsn/import_blocks.rs
Labels: bug, networking, node

#3520 Log more detailed failure info during DSN segment downloads
  shared/subspace-data-retrieval/src/segment_downloading.rs
Labels: networking, node

#3522 Capture fallible routes on XDM to mark the transfer as failed
  domains/pallets/messenger/src/messages.rs
  domains/pallets/transporter/src/lib.rs
Labels: audit-P1

#3531 Use helpful type alias
  Cargo.lock
  crates/pallet-subspace/src/mock.rs
  crates/sc-consensus-subspace/src/block_import.rs
  crates/sc-consensus-subspace/src/slot_worker.rs
  crates/sc-subspace-block-relay/Cargo.toml
  crates/sc-subspace-block-relay/src/consensus/relay.rs
  crates/sc-subspace-block-relay/src/consensus/types.rs
  crates/sp-consensus-subspace/src/lib.rs
  crates/sp-domains/src/core_api.rs
  crates/sp-domains/src/lib.rs
  crates/subspace-fake-runtime-api/src/lib.rs
  crates/subspace-malicious-operator/src/malicious_bundle_producer.rs
  crates/subspace-malicious-operator/src/malicious_domain_instance_starter.rs
  crates/subspace-node/src/commands/run/domain.rs
  crates/subspace-runtime-primitives/src/lib.rs
  crates/subspace-runtime/src/lib.rs
  crates/subspace-service/src/lib.rs
  crates/subspace-service/src/mmr/request_handler.rs
  crates/subspace-service/src/sync_from_dsn/import_blocks.rs
  domains/client/block-builder/Cargo.toml
  domains/client/block-builder/src/custom_api.rs
  domains/client/block-preprocessor/src/lib.rs
  domains/client/block-preprocessor/src/stateless_runtime.rs
  domains/client/domain-operator/src/aux_schema.rs
  domains/client/domain-operator/src/domain_block_processor.rs
  domains/client/domain-operator/src/domain_bundle_producer.rs
  domains/client/domain-operator/src/domain_bundle_proposer.rs
  domains/client/domain-operator/src/domain_worker.rs
  domains/client/domain-operator/src/fraud_proof.rs
  domains/client/domain-operator/src/lib.rs
  domains/client/domain-operator/src/tests.rs
  domains/client/relayer/Cargo.toml
  domains/client/relayer/src/lib.rs
  domains/runtime/auto-id/src/lib.rs
  domains/runtime/evm/src/lib.rs
  domains/service/src/domain.rs
  domains/service/src/network.rs
  domains/test/runtime/auto-id/src/lib.rs
  domains/test/runtime/evm/src/lib.rs
  domains/test/service/src/domain.rs
  test/subspace-test-runtime/src/lib.rs
  test/subspace-test-service/src/lib.rs
Labels: refactor

#3525 Fix retrieving multi-piece objects ending in the final segment piece
  shared/subspace-data-retrieval/src/object_fetcher/partial_object.rs
  shared/subspace-data-retrieval/src/object_fetcher/tests.rs
Labels: bug, networking

#3526 Fix unstable CI by waiting for node to shut down
  domains/client/domain-operator/src/tests.rs
  domains/test/service/src/domain.rs
  test/subspace-test-service/src/lib.rs
Labels: bug, node, devops

#3534 ensure no partial state when XDM is being processed
  domains/pallets/messenger/src/lib.rs
  domains/pallets/transporter/src/lib.rs
Labels: audit-P1

#3528 Block preprocessor improvements
  crates/sp-domains/src/core_api.rs
  crates/subspace-fake-runtime-api/src/lib.rs
  crates/subspace-runtime/src/lib.rs
  domains/client/block-preprocessor/src/lib.rs
  domains/client/block-preprocessor/src/stateless_runtime.rs
  domains/primitives/messenger/src/lib.rs
  domains/runtime/auto-id/src/lib.rs
  domains/runtime/evm/src/lib.rs
  domains/test/runtime/auto-id/src/lib.rs
  domains/test/runtime/evm/src/lib.rs
  test/subspace-test-runtime/src/lib.rs
Labels: execution, audit-P2

#3521 Track segment indexes correctly during DSN sync
  crates/subspace-core-primitives/src/segments.rs
  crates/subspace-service/src/sync_from_dsn.rs
  crates/subspace-service/src/sync_from_dsn/import_blocks.rs
  crates/subspace-service/src/sync_from_dsn/segment_header_downloader.rs
  domains/client/domain-operator/src/snap_sync.rs
Labels: bug, node, audit-P1

#3556 Add extra unbans to test_domain_tx_propagate
  domains/client/domain-operator/src/tests.rs
  domains/test/service/src/domain.rs
Labels: bug
