Repository autonomys/subspace, pull requests merged in 2025-03, with the labels that each got.

#3402 Use the current block number as the nonce of the new account
  crates/pallet-domains/src/tests.rs
  crates/sp-domains-fraud-proof/src/tests.rs
  crates/subspace-malicious-operator/src/malicious_bundle_producer.rs
  crates/subspace-runtime-primitives/src/utility.rs
  crates/subspace-runtime/src/lib.rs
  domains/client/domain-operator/src/tests.rs
  domains/runtime/auto-id/src/lib.rs
  domains/runtime/evm/src/lib.rs
  domains/test/runtime/auto-id/src/lib.rs
  domains/test/runtime/evm/src/lib.rs
  domains/test/service/src/domain.rs
  test/subspace-test-runtime/src/lib.rs
  test/subspace-test-service/src/lib.rs
Labels: bug, execution, audit-P2

#3414 Add estimated storage fee to eth_estimateGas RPC
  domains/client/domain-operator/src/lib.rs
  domains/client/domain-operator/src/tests.rs
  domains/runtime/evm/src/lib.rs
  domains/test/runtime/evm/src/lib.rs
Labels: bug, execution

#3420 Remove duplicate dependencies from recent polkadot-stable2412-1 upgrade
  Cargo.lock
  Cargo.toml
  crates/subspace-networking/src/behavior.rs
  crates/subspace-networking/src/lib.rs
  crates/subspace-networking/src/node_runner.rs
  crates/subspace-networking/src/protocols/request_response/request_response_factory.rs
  crates/subspace-networking/src/utils/piece_provider.rs
Labels: refactor

#3425 Revert incorrect EVM gas fee estimates
  domains/client/domain-operator/Cargo.toml
  domains/client/domain-operator/src/tests.rs
  domains/runtime/evm/src/lib.rs
  domains/test/runtime/evm/src/lib.rs
Labels: bug, execution

#3427 Check no-std/std and other missing features in CI
  .github/workflows/rust.yml
Labels: devops

#3434 Remove unnecessary CI platforms for runtime build job
  .github/workflows/rust.yml
Labels: devops

#3428 Upgrade to new libp2p API and Event Segments
  Cargo.lock
  Cargo.toml
  crates/pallet-domains/src/tests.rs
  crates/pallet-rewards/src/mock.rs
  crates/pallet-subspace/src/mock.rs
  crates/subspace-runtime-primitives/src/lib.rs
  crates/subspace-runtime/src/lib.rs
  domains/pallets/auto-id/src/tests.rs
  domains/pallets/domain-id/Cargo.toml
  domains/pallets/domain-id/src/tests.rs
  domains/pallets/executive/Cargo.toml
  domains/pallets/executive/src/lib.rs
  domains/pallets/executive/src/migrations.rs
  domains/pallets/executive/src/mock.rs
  domains/pallets/messenger/Cargo.toml
  domains/pallets/messenger/src/mock.rs
  domains/pallets/transporter/Cargo.toml
  domains/pallets/transporter/src/mock.rs
  domains/runtime/auto-id/src/lib.rs
  domains/runtime/evm/src/lib.rs
  domains/test/runtime/auto-id/src/lib.rs
  domains/test/runtime/evm/src/lib.rs
  test/subspace-test-runtime/src/lib.rs
Labels: networking, execution

#3442 Check crates without dependents individually, and run clippy on them
  .github/workflows/rust.yml
  crates/subspace-gateway/Cargo.toml
  domains/pallets/executive/src/migrations.rs
Labels: improvement, devops

#3443 include multisig calls while checking for balance transfers, extensibly
  Cargo.lock
  crates/subspace-runtime-primitives/Cargo.toml
  crates/subspace-runtime-primitives/src/utility.rs
  crates/subspace-runtime/src/lib.rs
  crates/subspace-runtime/src/object_mapping.rs
  crates/subspace-runtime/src/signed_extensions.rs
  domains/pallets/evm-tracker/Cargo.toml
  domains/pallets/evm-tracker/src/create_contract.rs
  domains/runtime/evm/src/lib.rs
  domains/test/runtime/evm/src/lib.rs
  test/subspace-test-runtime/Cargo.toml
  test/subspace-test-runtime/src/lib.rs
  test/subspace-test-service/src/lib.rs
Labels: bug, execution, audit-P3

#3447 Introduce V1 message format for XDM
  crates/subspace-runtime-primitives/src/lib.rs
  crates/subspace-runtime/src/lib.rs
  domains/pallets/messenger/src/fees.rs
  domains/pallets/messenger/src/lib.rs
  domains/pallets/messenger/src/messages.rs
  domains/pallets/messenger/src/mock.rs
  domains/pallets/transporter/src/mock.rs
  domains/primitives/messenger/src/endpoint.rs
  domains/primitives/messenger/src/messages.rs
  domains/runtime/auto-id/src/lib.rs
  domains/runtime/evm/src/lib.rs
  domains/test/runtime/auto-id/src/lib.rs
  domains/test/runtime/evm/src/lib.rs
  test/subspace-test-runtime/src/lib.rs
Labels: audit-P2

#3439 Enforce recursion depth limit when manually decoding runtime calls
  crates/pallet-domains/src/lib.rs
  crates/sp-domains-fraud-proof/src/host_functions.rs
  crates/subspace-runtime-primitives/src/lib.rs
  crates/subspace-runtime/src/lib.rs
  crates/subspace-runtime/src/object_mapping.rs
  domains/runtime/auto-id/src/lib.rs
  domains/runtime/evm/src/lib.rs
  domains/test/runtime/auto-id/src/lib.rs
  domains/test/runtime/evm/src/lib.rs
  test/subspace-test-runtime/src/lib.rs
Labels: bug, execution, audit-P2

#3451 Fix incorrect peer port autodetection and substream limit exceeded errors
  Cargo.lock
  Cargo.toml
  crates/subspace-networking/src/behavior/persistent_parameters.rs
  crates/subspace-networking/src/node_runner.rs
Labels: bug, networking

#3362 Stop downloading entire segments when retrieving objects
  Cargo.lock
  crates/subspace-archiving/tests/integration/archiver.rs
  crates/subspace-core-primitives/src/pieces.rs
  crates/subspace-gateway/Cargo.toml
  crates/subspace-gateway/src/commands.rs
  shared/subspace-data-retrieval/Cargo.toml
  shared/subspace-data-retrieval/src/lib.rs
  shared/subspace-data-retrieval/src/object_fetcher.rs
  shared/subspace-data-retrieval/src/object_fetcher/partial_object.rs
  shared/subspace-data-retrieval/src/object_fetcher/segment_header.rs
  shared/subspace-data-retrieval/src/object_fetcher/tests.rs
  shared/subspace-data-retrieval/src/piece_getter.rs
Labels: bug, improvement, audit-P3
