Repository autonomys/subspace, pull requests merged in 2025-06, with the labels that each got.

#3558 Improve random walker example
  crates/subspace-networking/examples/random-walker.rs
Labels: improvement

#3569 Clarify and extend CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#3554 Add benchmark weights for permissioned EVM extension
  Cargo.lock
  crates/subspace-node/Cargo.toml
  domains/pallets/evm-tracker/Cargo.toml
  domains/pallets/evm-tracker/src/benchmarking.rs
  domains/pallets/evm-tracker/src/create_contract.rs
  domains/pallets/evm-tracker/src/lib.rs
  domains/pallets/evm-tracker/src/weights.rs
  domains/runtime/evm/Cargo.toml
  domains/runtime/evm/src/lib.rs
  domains/test/runtime/evm/src/lib.rs
Labels: execution

#3589 Reject trailing bytes during unchecked extrinsic decoding
  domains/runtime/auto-id/src/lib.rs
  domains/runtime/evm/src/lib.rs
  domains/test/runtime/auto-id/src/lib.rs
  domains/test/runtime/evm/src/lib.rs
Labels: bug, execution

#3591 Do checked arithmetic during CheckNonce
  domains/pallets/evm-tracker/src/check_nonce.rs
  domains/pallets/messenger/src/lib.rs
  domains/primitives/runtime/src/lib.rs
  domains/runtime/evm/src/lib.rs
  domains/test/runtime/evm/src/lib.rs
Labels: bug, execution

#3575 Retry segment download at the start of snap sync
  crates/subspace-farmer-components/src/segment_reconstruction.rs
  crates/subspace-service/src/sync_from_dsn/import_blocks.rs
  crates/subspace-service/src/sync_from_dsn/snap_sync.rs
  shared/subspace-data-retrieval/Cargo.toml
  shared/subspace-data-retrieval/src/segment_downloading.rs
Labels: improvement, networking

#3595 Fix incorrect `NominatorCount` that cause operator cleanup before all nominator unlock
  crates/pallet-domains/src/lib.rs
  crates/pallet-domains/src/staking.rs
  crates/pallet-domains/src/staking_epoch.rs
Labels: execution, audit-P2

#3592 Automatically check for unused dependencies in CI
  .github/workflows/rust.yml
  Cargo.lock
  Cargo.toml
  crates/sp-objects/Cargo.toml
  crates/subspace-proof-of-space/Cargo.toml
  domains/pallets/evm-tracker/Cargo.toml
  shared/subspace-kzg/Cargo.toml
  shared/subspace-proof-of-space-gpu/Cargo.toml
Labels: devops

#3600 Make all node version git hashes the same length
  .github/workflows/snapshot-build.yml
Labels: improvement, nice-to-have

#3602 Add or document missing weights for frequent calls
  domains/pallets/block-fees/src/lib.rs
  domains/pallets/domain-check-weight/src/lib.rs
  domains/runtime/auto-id/src/lib.rs
  domains/runtime/evm/src/lib.rs
  domains/test/runtime/auto-id/src/lib.rs
  domains/test/runtime/evm/src/lib.rs
Labels: improvement, execution

#3608 Make share overflow errors and missing share prices explicit
  crates/pallet-domains/src/staking.rs
  crates/pallet-domains/src/staking_epoch.rs
Labels: bug, execution
