Repository autonomys/subspace, pull requests merged in 2025-09, with the labels that each got.

#3689 Ensure nominator reward amount is infaliable when their calculated stake is less than actual deposit
  crates/pallet-domains/src/staking_epoch.rs
Labels: execution

#3704 Temporarily remove Windows binary signing
  .github/workflows/snapshot-build.yml
Labels: devops

#3699 Deactivate and Reregister operators through Sudo
  crates/pallet-domains/src/benchmarking.rs
  crates/pallet-domains/src/extensions.rs
  crates/pallet-domains/src/lib.rs
  crates/pallet-domains/src/staking.rs
  crates/pallet-domains/src/staking_epoch.rs
  crates/pallet-domains/src/tests.rs
  crates/pallet-domains/src/weights.rs
  crates/subspace-runtime-primitives/src/weights/balance_transfer_check_extension.rs
  crates/subspace-runtime/src/lib.rs
  crates/subspace-runtime/src/weights/frame_system.rs
  crates/subspace-runtime/src/weights/pallet_balances.rs
  crates/subspace-runtime/src/weights/pallet_collective.rs
  crates/subspace-runtime/src/weights/pallet_domains.rs
  crates/subspace-runtime/src/weights/pallet_messenger.rs
  crates/subspace-runtime/src/weights/pallet_messenger_from_domains_extension.rs
  crates/subspace-runtime/src/weights/pallet_mmr.rs
  crates/subspace-runtime/src/weights/pallet_multisig.rs
  crates/subspace-runtime/src/weights/pallet_preimage.rs
  crates/subspace-runtime/src/weights/pallet_rewards.rs
  crates/subspace-runtime/src/weights/pallet_runtime_configs.rs
  crates/subspace-runtime/src/weights/pallet_scheduler.rs
  crates/subspace-runtime/src/weights/pallet_subspace.rs
  crates/subspace-runtime/src/weights/pallet_subspace_extension.rs
  crates/subspace-runtime/src/weights/pallet_sudo.rs
  crates/subspace-runtime/src/weights/pallet_timestamp.rs
  crates/subspace-runtime/src/weights/pallet_transaction_payment.rs
  crates/subspace-runtime/src/weights/pallet_transporter.rs
  crates/subspace-runtime/src/weights/pallet_utility.rs
  domains/pallets/evm-tracker/src/weights/pallet_evm_tracker.rs
  domains/runtime/auto-id/src/weights/domain_pallet_executive.rs
  domains/runtime/auto-id/src/weights/frame_system.rs
  domains/runtime/auto-id/src/weights/pallet_auto_id.rs
  domains/runtime/auto-id/src/weights/pallet_balances.rs
  domains/runtime/auto-id/src/weights/pallet_messenger.rs
  domains/runtime/auto-id/src/weights/pallet_messenger_between_domains_extension.rs
  domains/runtime/auto-id/src/weights/pallet_messenger_from_consensus_extension.rs
  domains/runtime/auto-id/src/weights/pallet_timestamp.rs
  domains/runtime/auto-id/src/weights/pallet_transaction_payment.rs
  domains/runtime/auto-id/src/weights/pallet_transporter.rs
  domains/runtime/auto-id/src/weights/pallet_utility.rs
  domains/runtime/evm/src/weights/domain_pallet_executive.rs
  domains/runtime/evm/src/weights/frame_system.rs
  domains/runtime/evm/src/weights/pallet_balances.rs
  domains/runtime/evm/src/weights/pallet_evm.rs
  domains/runtime/evm/src/weights/pallet_messenger.rs
  domains/runtime/evm/src/weights/pallet_messenger_between_domains_extension.rs
  domains/runtime/evm/src/weights/pallet_messenger_from_consensus_extension.rs
  domains/runtime/evm/src/weights/pallet_timestamp.rs
  domains/runtime/evm/src/weights/pallet_transaction_payment.rs
  domains/runtime/evm/src/weights/pallet_transporter.rs
  domains/runtime/evm/src/weights/pallet_utility.rs
  test/subspace-test-runtime/src/lib.rs
Labels: audit-P2
