Repository autonomys/subspace, pull requests merged in 2025-07, with the labels that each got.

#3610 Use higher default weight for pallet_transaction_fees init
  crates/pallet-transaction-fees/src/weights.rs
Labels: bug, improvement, execution

#3615 Reduce "actively using dsn peers" log frequency
  crates/subspace-networking/src/node_runner.rs
Labels: improvement, networking

#3611 Remove complex stake withdraw options from backend
  crates/pallet-domains/src/benchmarking.rs
  crates/pallet-domains/src/lib.rs
  crates/pallet-domains/src/staking.rs
  crates/pallet-domains/src/staking_epoch.rs
Labels: improvement, execution

#3617 Make test CI more robust against network failures
  .github/workflows/rust.yml
Labels: bug, devops

#3616 Retry segment downloads in node DSN sync and farmer piece reconstruction
  crates/subspace-farmer-components/src/segment_reconstruction.rs
  crates/subspace-service/src/sync_from_dsn/import_blocks.rs
  crates/subspace-service/src/sync_from_dsn/snap_sync.rs
  shared/subspace-data-retrieval/src/segment_downloading.rs
Labels: bug, farmer, networking, node

#3633 Temporarily disable unstable tests on macOS, and fix unstable proptests
  Cargo.lock
  Cargo.toml
  crates/pallet-domains/Cargo.toml
  crates/pallet-domains/proptest-regressions/staking.txt
  crates/pallet-domains/src/staking.rs
  domains/client/domain-operator/src/tests.rs
Labels: bug, execution

#3634 Add nominator position proptest
  crates/pallet-domains/proptest-regressions/nominator_position.txt
  crates/pallet-domains/src/nominator_position.rs
  crates/pallet-domains/src/staking.rs
Labels: execution

#3638 Run benchmark check in CI, allow devs to run CI scripts locally
  .github/workflows/rust.yml
  crates/subspace-farmer/Cargo.toml
  crates/subspace-runtime-primitives/src/extension.rs
  crates/subspace-runtime-primitives/src/extension/benchmarking.rs
  crates/subspace-runtime/src/lib.rs
  scripts/bump-versions.sh
  scripts/check-crates-individually.sh
  scripts/find-unused-deps.sh
  scripts/runtime-benchmark.sh
  shared/subspace-proof-of-space-gpu/Cargo.toml
Labels: bug, devops, execution

#3640 Cleanup old taurus compatibility code
  crates/pallet-domains/src/block_tree.rs
  crates/pallet-domains/src/lib.rs
  crates/pallet-domains/src/migrations.rs
  crates/pallet-domains/src/migrations/v1_to_v5.rs
  crates/pallet-domains/src/staking.rs
  crates/sp-domains/src/lib.rs
  crates/subspace-fake-runtime-api/src/lib.rs
  crates/subspace-runtime/src/lib.rs
  domains/client/block-builder/src/genesis_block_builder.rs
  domains/client/block-preprocessor/src/inherents.rs
  domains/client/block-preprocessor/src/lib.rs
  domains/client/cross-domain-message-gossip/src/message_listener.rs
  domains/client/domain-operator/src/domain_bundle_proposer.rs
  domains/client/relayer/src/lib.rs
  domains/client/relayer/src/worker.rs
  domains/pallets/messenger/src/fees.rs
  domains/pallets/messenger/src/lib.rs
  domains/pallets/messenger/src/migrations.rs
  domains/pallets/messenger/src/migrations/v0_to_v1.rs
  domains/pallets/messenger/src/migrations/v1_to_v2.rs
  domains/pallets/messenger/src/mock.rs
  domains/pallets/transporter/src/lib.rs
  domains/pallets/transporter/src/mock.rs
  domains/primitives/messenger/src/lib.rs
  domains/primitives/messenger/src/messages.rs
  domains/runtime/auto-id/src/lib.rs
  domains/runtime/evm/src/lib.rs
  domains/test/runtime/auto-id/src/lib.rs
  domains/test/runtime/evm/src/lib.rs
  test/subspace-test-runtime/src/lib.rs
Labels: breaking-execution

#3646 Avoid Fn generics in bundle versions
  crates/pallet-domains/src/lib.rs
  crates/pallet-domains/src/tests.rs
  crates/subspace-node/src/chain_spec.rs
  crates/subspace-node/src/commands/run/domain.rs
  crates/subspace-node/src/domain/auto_id_chain_spec.rs
Labels: refactor, execution

#3650 Add byte sizes to piece cache sync progress
  Cargo.lock
  crates/sc-consensus-subspace/Cargo.toml
  crates/sc-consensus-subspace/src/archiver.rs
  crates/subspace-farmer/src/farmer_cache.rs
  crates/subspace-networking/src/utils/piece_provider.rs
  shared/subspace-data-retrieval/src/segment_downloading.rs
Labels: farmer, improvement, nice-to-have

#3654 fix: now farmer piece cache sync percentage base on total cache size
  crates/subspace-farmer/src/farmer_cache.rs
Labels: bug, farmer, nice-to-have
