Repository autonomys/subspace, pull requests merged in 2025-04, with the labels that each got.

#3458 Add domain starting checks
  Cargo.lock
  crates/subspace-malicious-operator/src/bin/subspace-malicious-operator.rs
  crates/subspace-malicious-operator/src/chain_spec.rs
  crates/subspace-malicious-operator/src/lib.rs
  crates/subspace-malicious-operator/src/malicious_domain_instance_starter.rs
  crates/subspace-node/Cargo.toml
  crates/subspace-node/src/commands/run.rs
  crates/subspace-node/src/commands/run/domain.rs
  domains/client/domain-operator/src/fetch_domain_bootstrap_info.rs
  domains/client/domain-operator/src/tests.rs
  domains/service/src/domain.rs
  domains/test/service/src/chain_spec.rs
  domains/test/service/src/domain.rs
  test/subspace-test-service/src/lib.rs
Labels: execution

#3485 Domain snap sync fixes
  Cargo.lock
  crates/sc-domains/Cargo.toml
  crates/sc-domains/src/domain_block_er.rs
  crates/sc-domains/src/domain_block_er/execution_receipt_protocol.rs
  crates/sc-domains/src/domain_block_er/receipt_receiver.rs
  crates/sc-domains/src/lib.rs
  crates/subspace-malicious-operator/src/malicious_domain_instance_starter.rs
  crates/subspace-node/src/commands/run.rs
  crates/subspace-node/src/commands/run/domain.rs
  crates/subspace-service/src/lib.rs
  domains/client/domain-operator/src/lib.rs
  domains/client/domain-operator/src/operator.rs
  domains/client/domain-operator/src/snap_sync.rs
  domains/service/Cargo.toml
  domains/service/src/domain.rs
  domains/service/src/network.rs
  domains/test/service/src/domain.rs
Labels: audit-P1

#3472 Re-use the last piece for the next object in a batch
  Cargo.lock
  crates/subspace-core-primitives/src/objects.rs
  crates/subspace-gateway-rpc/README.md
  crates/subspace-gateway-rpc/src/lib.rs
  crates/subspace-gateway/src/commands/http/server.rs
  crates/subspace-service/Cargo.toml
  crates/subspace-service/src/lib.rs
  shared/subspace-data-retrieval/Cargo.toml
  shared/subspace-data-retrieval/src/object_fetcher.rs
  shared/subspace-data-retrieval/src/object_fetcher/segment_header.rs
  shared/subspace-data-retrieval/src/object_fetcher/tests.rs
  shared/subspace-data-retrieval/src/piece_getter.rs
  test/subspace-test-runtime/src/lib.rs
Labels: improvement, networking

#3490 Only take XDM weight tags if we've actually taken an inbox response
  domains/pallets/messenger/src/fees.rs
Labels: bug, execution

#3491 Fix padding and segment header checks in object retrieval tests
  crates/subspace-core-primitives/src/pieces.rs
  crates/subspace-core-primitives/src/segments.rs
  shared/subspace-data-retrieval/src/object_fetcher/tests.rs
  shared/subspace-logging/src/lib.rs
Labels: improvement

#3495 Domain snap sync
  Cargo.lock
  crates/pallet-domains/Cargo.toml
  crates/pallet-domains/src/block_tree.rs
  crates/pallet-domains/src/lib.rs
  crates/pallet-domains/src/migrations.rs
  crates/sp-domains/src/lib.rs
  crates/subspace-runtime/src/lib.rs
  crates/subspace-service/src/lib.rs
  crates/subspace-service/src/mmr/request_handler.rs
  crates/subspace-service/src/mmr/sync.rs
  crates/subspace-service/src/sync_from_dsn.rs
  crates/subspace-service/src/sync_from_dsn/import_blocks.rs
  crates/subspace-service/src/sync_from_dsn/piece_validator.rs
  crates/subspace-service/src/sync_from_dsn/segment_header_downloader.rs
  crates/subspace-service/src/sync_from_dsn/snap_sync.rs
  domains/client/block-builder/Cargo.toml
  domains/client/block-builder/src/genesis_block_builder.rs
  domains/client/block-builder/src/lib.rs
  domains/client/domain-operator/src/aux_schema.rs
  domains/client/domain-operator/src/domain_block_processor.rs
  domains/client/domain-operator/src/fetch_domain_bootstrap_info.rs
  domains/client/domain-operator/src/lib.rs
  domains/client/domain-operator/src/operator.rs
  domains/client/domain-operator/src/snap_sync.rs
  domains/client/domain-operator/src/utils.rs
  domains/service/Cargo.toml
  domains/service/src/domain.rs
Labels: audit-P1

#3492 Add a timeout to inbound libp2p-kad substreams
  Cargo.lock
  Cargo.toml
Labels: bug, networking, performance
