Repository autonomys/subspace, pull requests merged in 2025-08, with the labels that each got.

#3660 Improve farmer piece cache performance, by avoiding segment header cache reader starvation
  crates/subspace-farmer/src/bin/subspace-farmer/commands/shared/network.rs
  crates/subspace-farmer/src/node_client.rs
  crates/subspace-farmer/src/node_client/caching_proxy_node_client.rs
  crates/subspace-farmer/src/node_client/rpc_node_client.rs
Labels: bug, farmer, networking, performance

#3661 Fix missing share price for de-registered operators
  crates/pallet-domains/src/benchmarking.rs
  crates/pallet-domains/src/lib.rs
  crates/pallet-domains/src/nominator_position.rs
  crates/pallet-domains/src/staking.rs
  crates/pallet-domains/src/staking_epoch.rs
Labels: bug, consensus

#3678 Deduplicate set_exit_on_panic
  Cargo.lock
  crates/subspace-bootstrap-node/src/main.rs
  crates/subspace-farmer/Cargo.toml
  crates/subspace-farmer/src/bin/subspace-farmer/main.rs
  crates/subspace-gateway/src/commands.rs
  crates/subspace-gateway/src/main.rs
  crates/subspace-malicious-operator/Cargo.toml
  crates/subspace-malicious-operator/src/bin/subspace-malicious-operator.rs
  crates/subspace-networking/examples/benchmark.rs
  crates/subspace-networking/examples/get-peers.rs
  crates/subspace-networking/examples/metrics.rs
  crates/subspace-networking/examples/networking.rs
  crates/subspace-networking/examples/random-walker.rs
  crates/subspace-networking/examples/requests.rs
  crates/subspace-node/src/commands.rs
  crates/subspace-node/src/commands/shared.rs
  crates/subspace-node/src/main.rs
  shared/subspace-process/src/lib.rs
Labels: refactor

#3677 Release farmer cache piece permit after errors
  crates/subspace-farmer/src/farmer_cache.rs
Labels: bug, farmer

#3681 Accept EVM ChainID as parameter through Domain Instantiation
  crates/pallet-domains/src/benchmarking.rs
  crates/pallet-domains/src/domain_registry.rs
  crates/pallet-domains/src/lib.rs
  crates/pallet-domains/src/migrations.rs
  crates/pallet-domains/src/migrations/v5_to_v6.rs
  crates/pallet-domains/src/runtime_registry.rs
  crates/pallet-domains/src/staking.rs
  crates/pallet-domains/src/tests.rs
  crates/sp-domains/src/lib.rs
  crates/subspace-malicious-operator/src/chain_spec.rs
  crates/subspace-node/src/chain_spec.rs
  crates/subspace-node/src/domain/auto_id_chain_spec.rs
  crates/subspace-node/src/domain/cli.rs
  crates/subspace-node/src/domain/evm_chain_spec.rs
  crates/subspace-runtime/src/lib.rs
  domains/primitives/runtime/src/lib.rs
  test/subspace-test-client/src/auto_id_domain_chain_spec.rs
  test/subspace-test-client/src/evm_domain_chain_spec.rs
Labels: execution, audit-P3

#3682 Improve farmer piece cache writing performance, and add debugging logs
  crates/subspace-farmer/src/cluster/controller/stream_map.rs
  crates/subspace-farmer/src/disk_piece_cache.rs
  crates/subspace-farmer/src/farm.rs
  crates/subspace-farmer/src/farmer_cache.rs
  crates/subspace-farmer/src/farmer_piece_getter.rs
  crates/subspace-farmer/src/single_disk_farm/plot_cache.rs
  crates/subspace-networking/src/node_runner.rs
  domains/client/block-preprocessor/src/lib.rs
Labels: refactor, performance
