Repository autonomys/subspace, pull requests merged in 2025-02, with the labels that each got.

#3350 Add contract creation allow lists to EVM domains
  Cargo.lock
  crates/pallet-domains/src/benchmarking.rs
  crates/pallet-domains/src/domain_registry.rs
  crates/pallet-domains/src/lib.rs
  crates/pallet-domains/src/runtime_registry.rs
  crates/pallet-domains/src/staking.rs
  crates/pallet-domains/src/tests.rs
  crates/sp-domains-fraud-proof/Cargo.toml
  crates/sp-domains-fraud-proof/src/tests.rs
  crates/sp-domains/src/lib.rs
  crates/sp-domains/src/storage.rs
  crates/sp-domains/src/test_ethereum.rs
  crates/sp-domains/src/test_ethereum_tx.rs
  crates/subspace-malicious-operator/src/chain_spec.rs
  crates/subspace-node/src/chain_spec.rs
  crates/subspace-node/src/domain/auto_id_chain_spec.rs
  crates/subspace-node/src/domain/cli.rs
  crates/subspace-node/src/domain/evm_chain_spec.rs
  crates/subspace-runtime-primitives/Cargo.toml
  crates/subspace-runtime-primitives/src/lib.rs
  crates/subspace-runtime-primitives/src/utility.rs
  crates/subspace-runtime/src/lib.rs
  crates/subspace-runtime/src/object_mapping.rs
  crates/subspace-runtime/src/signed_extensions.rs
  domains/client/domain-operator/Cargo.toml
  domains/client/domain-operator/src/lib.rs
  domains/client/domain-operator/src/tests.rs
  domains/pallets/evm-tracker/Cargo.toml
  domains/pallets/evm-tracker/src/check_nonce.rs
  domains/pallets/evm-tracker/src/create_contract.rs
  domains/pallets/evm-tracker/src/lib.rs
  domains/pallets/evm-tracker/src/traits.rs
  domains/pallets/evm_nonce_tracker/src/lib.rs
  domains/primitives/runtime/src/lib.rs
  domains/runtime/evm/Cargo.toml
  domains/runtime/evm/src/lib.rs
  domains/test/primitives/Cargo.toml
  domains/test/primitives/src/lib.rs
  domains/test/runtime/evm/Cargo.toml
  domains/test/runtime/evm/src/lib.rs
  domains/test/service/src/domain.rs
  domains/test/service/src/lib.rs
  test/subspace-test-client/src/auto_id_domain_chain_spec.rs
  test/subspace-test-client/src/evm_domain_chain_spec.rs
  test/subspace-test-runtime/src/lib.rs
Labels: bug, enhancement, execution, audit-P2

#3368 Fix inconsistency of bundle digest generation and add invalid fraud proof integration test
  crates/sp-domains-fraud-proof/src/host_functions.rs
  domains/client/domain-operator/src/domain_block_processor.rs
  domains/client/domain-operator/src/fraud_proof.rs
  domains/client/domain-operator/src/tests.rs
Labels: bug, execution, audit-P1

#3367 Fix second segment offset in object retrieval, other minor cleanups
  crates/pallet-domains/src/domain_registry.rs
  crates/pallet-domains/src/runtime_registry.rs
  crates/pallet-domains/src/staking.rs
  crates/pallet-domains/src/tests.rs
  crates/sc-consensus-subspace-rpc/src/lib.rs
  crates/sc-consensus-subspace/src/lib.rs
  crates/sp-domains-fraud-proof/src/lib.rs
  crates/subspace-core-primitives/src/objects.rs
  crates/subspace-gateway/src/commands/http/server.rs
  crates/subspace-rpc-primitives/src/lib.rs
  domains/client/domain-operator/src/domain_worker.rs
  domains/client/domain-operator/src/lib.rs
  domains/client/domain-operator/src/tests.rs
  domains/pallets/evm-tracker/src/lib.rs
  domains/test/service/src/domain.rs
  shared/subspace-data-retrieval/src/object_fetcher.rs
  shared/subspace-data-retrieval/src/piece_fetcher.rs
  test/subspace-test-service/src/lib.rs
Labels: bug, refactor

#3372 Finalize domain blocks and default domain block and state pruning
  Cargo.lock
  crates/subspace-malicious-operator/src/malicious_domain_instance_starter.rs
  crates/subspace-node/Cargo.toml
  crates/subspace-node/src/commands/run.rs
  crates/subspace-node/src/commands/run/domain.rs
  crates/subspace-runtime-primitives/src/lib.rs
  crates/subspace-runtime/src/lib.rs
  domains/client/domain-operator/src/aux_schema.rs
  domains/client/domain-operator/src/bundle_processor.rs
  domains/client/domain-operator/src/domain_block_processor.rs
  domains/client/domain-operator/src/lib.rs
  domains/client/domain-operator/src/operator.rs
  domains/client/domain-operator/src/snap_sync.rs
  domains/client/domain-operator/src/tests.rs
  domains/service/src/domain.rs
  domains/test/service/Cargo.toml
  domains/test/service/src/domain.rs
  test/subspace-test-primitives/src/lib.rs
  test/subspace-test-runtime/src/lib.rs
Labels: audit-P3

#3369 Fraud proof naming, test & comment cleanups
  crates/sc-proof-of-time/src/source/gossip.rs
  crates/sp-domains-fraud-proof/src/fraud_proof.rs
  crates/sp-domains-fraud-proof/src/host_functions.rs
  crates/sp-domains-fraud-proof/src/tests.rs
  crates/sp-domains-fraud-proof/src/verification.rs
  domains/client/block-preprocessor/src/lib.rs
  domains/client/cross-domain-message-gossip/src/gossip_worker.rs
  domains/client/cross-domain-message-gossip/src/message_listener.rs
  domains/client/domain-operator/src/aux_schema.rs
  domains/client/domain-operator/src/domain_block_processor.rs
  domains/client/domain-operator/src/fraud_proof.rs
  domains/client/domain-operator/src/tests.rs
Labels: refactor

#3375 Fix spelling error in `mock.rs`
  domains/pallets/messenger/src/mock.rs
  domains/pallets/transporter/src/mock.rs
Labels: refactor

#3380 XDM limit max number of future nonces allowed and relayer header backend fix
  domains/client/cross-domain-message-gossip/src/aux_schema.rs
  domains/client/cross-domain-message-gossip/src/message_listener.rs
  domains/client/relayer/src/lib.rs
  domains/pallets/messenger/src/lib.rs
Labels: audit-P2

#3378 Log segment header when archiver instantiation fails
  crates/sc-consensus-subspace/src/archiver.rs
  crates/subspace-archiving/src/archiver.rs
Labels: improvement

#3382 Ignore hickory-proto security issue until libp2p is upgraded
  .github/workflows/rustsec-audit.yml
Labels: devops, upstream

#3384 XDM: ensure relayer is only submitting XDMs that are within max nonce limit
  crates/subspace-fake-runtime-api/src/lib.rs
  crates/subspace-runtime/src/lib.rs
  domains/client/relayer/src/lib.rs
  domains/client/relayer/src/worker.rs
  domains/pallets/messenger/src/lib.rs
  domains/primitives/messenger/src/lib.rs
  domains/runtime/auto-id/src/lib.rs
  domains/runtime/evm/src/lib.rs
  domains/test/runtime/auto-id/src/lib.rs
  domains/test/runtime/evm/src/lib.rs
  test/subspace-test-runtime/src/lib.rs
Labels: audit-P3

#3381 Allow domain owner to change Private EVM contract creation allow list
  Cargo.lock
  crates/pallet-domains/src/domain_registry.rs
  crates/pallet-domains/src/lib.rs
  crates/pallet-domains/src/runtime_registry.rs
  crates/sp-domains-fraud-proof/src/fraud_proof.rs
  crates/sp-domains-fraud-proof/src/host_functions.rs
  crates/sp-domains-fraud-proof/src/lib.rs
  crates/sp-domains-fraud-proof/src/storage_proof.rs
  crates/sp-domains-fraud-proof/src/verification.rs
  crates/sp-domains/src/lib.rs
  crates/subspace-fake-runtime-api/src/lib.rs
  crates/subspace-node/src/chain_spec.rs
  crates/subspace-node/src/domain/evm_chain_spec.rs
  crates/subspace-runtime-primitives/src/lib.rs
  crates/subspace-runtime/src/lib.rs
  domains/client/block-preprocessor/Cargo.toml
  domains/client/block-preprocessor/src/inherents.rs
  domains/client/block-preprocessor/src/stateless_runtime.rs
  domains/client/domain-operator/src/fraud_proof.rs
  domains/client/domain-operator/src/tests.rs
  domains/pallets/evm-tracker/Cargo.toml
  domains/pallets/evm-tracker/src/lib.rs
  domains/primitives/evm-tracker/Cargo.toml
  domains/primitives/evm-tracker/src/lib.rs
  domains/primitives/runtime/src/lib.rs
  domains/runtime/evm/Cargo.toml
  domains/runtime/evm/src/lib.rs
  domains/test/runtime/evm/Cargo.toml
  domains/test/runtime/evm/src/lib.rs
  domains/test/service/src/domain.rs
  test/subspace-test-client/src/chain_spec.rs
  test/subspace-test-client/src/evm_domain_chain_spec.rs
  test/subspace-test-runtime/src/lib.rs
  test/subspace-test-service/src/lib.rs
Labels: improvement, breaking-runtime, audit-P2

#3360 pallet-domains storage migration for "Private EVM"
  crates/pallet-domains/src/lib.rs
  crates/pallet-domains/src/migration_v2_to_v3.rs
  crates/subspace-runtime/src/lib.rs
Labels: execution, breaking-runtime

#3395 Ensure to distribute the XDM fee regardless what the XDM execution result is
  domains/pallets/messenger/src/fees.rs
  domains/pallets/messenger/src/messages.rs
  domains/pallets/messenger/src/tests.rs
Labels: bug, execution, audit-P2

#3403 Refactor ensure_pruning_params variable names
  crates/subspace-node/src/chain_spec.rs
  crates/subspace-node/src/commands/run.rs
Labels: refactor

#3407 Add fallback decoding for the pallet-domains v3 storage migration
  crates/pallet-domains/src/domain_registry.rs
  crates/pallet-domains/src/lib.rs
  crates/pallet-domains/src/migration_v2_to_v3.rs
  crates/pallet-domains/src/staking.rs
Labels: bug, execution
