Repository autonomys/subspace, pull requests merged in 2025-01, with the labels that each got.

#3329 Storage proof: change BlockDigest to DomainRuntimeUpgrades
  crates/pallet-domains/src/lib.rs
  crates/pallet-domains/src/tests.rs
  crates/pallet-transaction-fees/src/lib.rs
  crates/sp-domains-fraud-proof/src/fraud_proof.rs
  crates/sp-domains-fraud-proof/src/storage_proof.rs
  crates/sp-domains-fraud-proof/src/verification.rs
  crates/sp-domains/src/lib.rs
  crates/subspace-runtime/src/lib.rs
  domains/client/domain-operator/src/fraud_proof.rs
  domains/client/domain-operator/src/tests.rs
  test/subspace-test-runtime/src/lib.rs
  test/subspace-test-service/src/lib.rs
Labels: execution, breaking-runtime

#3334 Update gateway HTTP server object mapping format
  Cargo.lock
  crates/sc-consensus-subspace-rpc/src/lib.rs
  crates/subspace-core-primitives/src/objects.rs
  crates/subspace-gateway-rpc/src/lib.rs
  crates/subspace-gateway/src/commands/http/server.rs
  crates/subspace-gateway/src/main.rs
  shared/subspace-data-retrieval/Cargo.toml
  shared/subspace-data-retrieval/src/object_fetcher.rs
  shared/subspace-data-retrieval/src/piece_fetcher.rs
Labels: improvement, breaking-node

#3336 Take reward of correct offending voter
  crates/pallet-subspace/src/lib.rs
  crates/pallet-subspace/src/tests.rs
Labels: need to audit

#3337 Add runtime_upgrades() runtime API for DomainRuntimeUpgrades
  crates/pallet-domains/src/lib.rs
  crates/sp-domains-fraud-proof/src/fraud_proof.rs
  crates/sp-domains-fraud-proof/src/storage_proof.rs
  crates/sp-domains-fraud-proof/src/verification.rs
  crates/sp-domains/src/lib.rs
  crates/subspace-fake-runtime-api/src/lib.rs
  crates/subspace-runtime/src/lib.rs
  domains/client/block-preprocessor/src/inherents.rs
  domains/client/domain-operator/src/fraud_proof.rs
  test/subspace-test-runtime/src/lib.rs
Labels: breaking-runtime

#3340 Get some runtime API values from combined fraud proof storage
  crates/pallet-domains/src/lib.rs
  crates/sp-domains-fraud-proof/src/storage_proof.rs
  crates/sp-domains/src/extrinsics.rs
  crates/sp-domains/src/lib.rs
  crates/subspace-fake-runtime-api/src/lib.rs
  crates/subspace-runtime/src/lib.rs
  domains/client/block-preprocessor/src/inherents.rs
  domains/client/domain-operator/src/domain_bundle_proposer.rs
  domains/client/domain-operator/src/tests.rs
  domains/test/primitives/src/lib.rs
  domains/test/runtime/auto-id/src/lib.rs
  domains/test/runtime/evm/src/lib.rs
  test/subspace-test-runtime/src/lib.rs
Labels: improvement, breaking-runtime

#3341 Remove unneeded compatibility code
  domains/client/block-preprocessor/src/lib.rs
Labels: execution

#3356 XDM: ensure max outgoing messages per channel is atleast one and ensure to return open channel that can still accept messages
  Cargo.lock
  crates/subspace-runtime/src/lib.rs
  domains/client/domain-operator/src/tests.rs
  domains/pallets/messenger/src/benchmarking.rs
  domains/pallets/messenger/src/lib.rs
  domains/pallets/messenger/src/messages.rs
  domains/pallets/messenger/src/mock.rs
  domains/pallets/messenger/src/tests.rs
  domains/pallets/transporter/src/mock.rs
  domains/primitives/runtime/src/lib.rs
  domains/runtime/auto-id/Cargo.toml
  domains/runtime/auto-id/src/lib.rs
  domains/runtime/evm/Cargo.toml
  domains/runtime/evm/src/lib.rs
  domains/test/runtime/auto-id/Cargo.toml
  domains/test/runtime/auto-id/src/lib.rs
  domains/test/runtime/evm/Cargo.toml
  domains/test/runtime/evm/src/lib.rs
  test/subspace-test-runtime/src/lib.rs
Labels: need to audit

#3359 Fix custom transaction error code clash, and make ethereum tests easier to write
  Cargo.lock
  crates/sp-domains-fraud-proof/Cargo.toml
  crates/sp-domains-fraud-proof/src/lib.rs
  crates/sp-domains-fraud-proof/src/tests.rs
  crates/sp-domains/Cargo.toml
  crates/sp-domains/src/lib.rs
  crates/sp-domains/src/test_ethereum.rs
  crates/sp-domains/src/test_ethereum_tx.rs
  crates/subspace-runtime/src/signed_extensions.rs
  domains/client/domain-operator/Cargo.toml
  domains/pallets/messenger/src/lib.rs
  domains/primitives/runtime/Cargo.toml
  domains/primitives/runtime/src/lib.rs
  domains/runtime/evm/Cargo.toml
  domains/runtime/evm/src/lib.rs
  domains/test/runtime/evm/Cargo.toml
  domains/test/runtime/evm/src/lib.rs
Labels: bug, refactor
